name: epi2melabs-nf-template-workflow
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat >=0.6.0
    - pysam >=0.17.0
    - fastcat
    - epi2melabs
